name: Generate static website

on:
  # Trigger manual
  workflow_dispatch:

jobs:
  generate-static-web:
    runs-on: ubuntu-latest
    environment: github-pages
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Build static website
        env: 
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          DJANGO_DEBUG: ${{ secrets.DJANGO_DEBUG }}
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
        run: |
          python manage.py migrate
          python manage.py collectstatic --noinput
          python manage.py distill-local docs --force
      - name: Git preparation
        run: |
          git config --global user.name github-actions
          git config --global user.email '$GITHUB_ACTOR@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GHA_TOKEN }}@github.com/$GITHUB_REPOSITORY
      - name: Commit to release/gh_pages
        run: |
          git add static/ docs/
          git stash
          git checkout -b release/gh_pages
          git stash pop
          git commit -m "Update the content" ||  true
          git push --force origin HEAD:$GITHUB_REF || true